"use node";

/**
 * Phase 3c / Wave 3a — Convex vectorIndex foundation.
 *
 * Powers the W3b vision-elimination pipeline + future catalog semantic
 * search. Embeddings are generated by Gemini (text-embedding-004, 768-dim)
 * for the three sources: item name, item description, item image. Image
 * embedding uses the same text-embedding-004 model fed with the image's
 * alt-text/caption — true multimodal embedding (multimodalembedding@001)
 * lives behind Vertex AI and isn't on the @google/generative-ai SDK
 * surface, so we degrade to caption-based embedding for the "image"
 * source_kind. Once Vertex SDK is wired up in a follow-up phase, swap the
 * implementation behind `embedImage` without changing the schema.
 *
 * GRACEFUL DEGRADATION: when GEMINI_API_KEY is missing the action no-ops
 * (logs a warning, returns null). Lets schema-only consumers compile/run
 * in dev / preview deployments without secrets.
 *
 * BACKFILL: manual-invoke only. No cron registered. Run via
 *   npx convex run item_embeddings:backfillEmbeddings '{"chunkSize":25,"maxChunks":4}'
 * Chunks are bounded so each invocation stays under Convex action budgets.
 */

import { v } from "convex/values";
import { internalAction, internalQuery, internalMutation } from "./_generated/server";
import { internal } from "./_generated/api";
import type { Doc, Id } from "./_generated/dataModel";

const EMBEDDING_MODEL = "text-embedding-004";
const EMBEDDING_DIMENSIONS = 768;

type SourceKind = "name" | "description" | "image";

// ────────────────────────────────────────────────────────────────────────────
// Gemini client (lazy — module load must not fail when key missing)
// ────────────────────────────────────────────────────────────────────────────

async function getGeminiClient(): Promise<{
  embedContent: (text: string) => Promise<number[] | null>;
} | null> {
  const key = process.env.GEMINI_API_KEY;
  if (!key) {
    console.warn("[item_embeddings] GEMINI_API_KEY missing — embedding action is a no-op");
    return null;
  }
  // Dynamic import so missing optional dependency doesn't break the bundle.
  const mod = await import("@google/generative-ai");
  const genAI = new mod.GoogleGenerativeAI(key);
  const model = genAI.getGenerativeModel({ model: EMBEDDING_MODEL });
  return {
    embedContent: async (text: string) => {
      if (!text || !text.trim()) return null;
      try {
        const res = await model.embedContent(text);
        const vec = res?.embedding?.values;
        if (!Array.isArray(vec) || vec.length !== EMBEDDING_DIMENSIONS) {
          console.warn(
            `[item_embeddings] Unexpected embedding shape: len=${vec?.length ?? "n/a"} (expected ${EMBEDDING_DIMENSIONS})`,
          );
          return null;
        }
        return vec as number[];
      } catch (err) {
        console.warn("[item_embeddings] Gemini embedContent failed:", err);
        return null;
      }
    },
  };
}

// ────────────────────────────────────────────────────────────────────────────
// Internal mutations & queries
// ────────────────────────────────────────────────────────────────────────────

/**
 * Write a single embedding row. Replaces any existing row with the same
 * (item_id, source_kind) tuple to keep the table idempotent.
 */
export const upsertEmbedding = internalMutation({
  args: {
    item_id: v.id("items"),
    embedding: v.array(v.float64()),
    embedding_model: v.string(),
    source_kind: v.union(v.literal("name"), v.literal("description"), v.literal("image")),
    source_ref: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const existing = await ctx.db
      .query("item_embeddings")
      .withIndex("by_item_and_kind", (q) =>
        q.eq("item_id", args.item_id).eq("source_kind", args.source_kind),
      )
      .first();
    const now = Date.now();
    if (existing) {
      await ctx.db.patch(existing._id, {
        embedding: args.embedding,
        embedding_model: args.embedding_model,
        source_ref: args.source_ref,
        generated_at: now,
      });
      return existing._id;
    }
    return await ctx.db.insert("item_embeddings", {
      item_id: args.item_id,
      embedding: args.embedding,
      embedding_model: args.embedding_model,
      source_kind: args.source_kind,
      source_ref: args.source_ref,
      generated_at: now,
    });
  },
});

/**
 * Returns true when (item_id, source_kind) is already embedded with the
 * current model. Backfill uses this to skip already-done rows.
 */
export const hasEmbedding = internalQuery({
  args: {
    item_id: v.id("items"),
    source_kind: v.union(v.literal("name"), v.literal("description"), v.literal("image")),
  },
  handler: async (ctx, args) => {
    const row = await ctx.db
      .query("item_embeddings")
      .withIndex("by_item_and_kind", (q) =>
        q.eq("item_id", args.item_id).eq("source_kind", args.source_kind),
      )
      .first();
    return !!row && row.embedding_model === EMBEDDING_MODEL;
  },
});

/**
 * Load a single item (used by generateEmbeddingsForItem to assemble the
 * three source strings).
 */
export const getItem = internalQuery({
  args: { item_id: v.id("items") },
  handler: async (ctx, args) => {
    return await ctx.db.get(args.item_id);
  },
});

/**
 * Paged list of items for backfill. Cursor-based via `_creationTime` for
 * stable ordering. Limit caps chunk size.
 */
export const listItemsForBackfill = internalQuery({
  args: {
    after_creation_time: v.optional(v.number()),
    limit: v.number(),
  },
  handler: async (ctx, args) => {
    const rows = await ctx.db
      .query("items")
      .filter((q) =>
        args.after_creation_time === undefined
          ? q.eq(q.field("_id"), q.field("_id"))
          : q.gt(q.field("_creationTime"), args.after_creation_time!),
      )
      .order("asc")
      .take(args.limit);
    return rows.map((r) => ({
      _id: r._id,
      _creationTime: r._creationTime,
      name_canonical: r.name_canonical,
      name_input: r.name_input,
      image_url: r.image_url,
    }));
  },
});

/**
 * Semantic search via vectorIndex. Internal — callers pass an already-
 * computed embedding. Vector search lives in the action runtime, NOT in
 * queries, so this is an internalAction wrapper exposed under the
 * search-similar name. (See searchSimilar below.)
 */

// ────────────────────────────────────────────────────────────────────────────
// Internal actions
// ────────────────────────────────────────────────────────────────────────────

/**
 * Generate ONE embedding (for the given content string) and upsert it.
 * No-op when GEMINI_API_KEY missing.
 */
export const generateEmbedding = internalAction({
  args: {
    item_id: v.id("items"),
    source_kind: v.union(v.literal("name"), v.literal("description"), v.literal("image")),
    content: v.string(),
    source_ref: v.optional(v.string()),
  },
  handler: async (ctx, args): Promise<{ ok: boolean; reason?: string }> => {
    const client = await getGeminiClient();
    if (!client) return { ok: false, reason: "no_api_key" };
    const vec = await client.embedContent(args.content);
    if (!vec) return { ok: false, reason: "empty_or_failed" };
    await ctx.runMutation(internal.item_embeddings.upsertEmbedding, {
      item_id: args.item_id,
      embedding: vec,
      embedding_model: EMBEDDING_MODEL,
      source_kind: args.source_kind,
      source_ref: args.source_ref,
    });
    return { ok: true };
  },
});

/**
 * Generate all three embeddings (name, description, image) for one item.
 * Skips sources that are already embedded with the current model OR have
 * no source content.
 */
export const generateEmbeddingsForItem = internalAction({
  args: { item_id: v.id("items") },
  handler: async (ctx, args): Promise<{ generated: number; skipped: number }> => {
    const item: Doc<"items"> | null = await ctx.runQuery(
      internal.item_embeddings.getItem,
      { item_id: args.item_id },
    );
    if (!item) return { generated: 0, skipped: 0 };

    const client = await getGeminiClient();
    if (!client) return { generated: 0, skipped: 0 };

    let generated = 0;
    let skipped = 0;

    const sources: Array<{
      kind: SourceKind;
      content: string;
      source_ref?: string;
    }> = [];

    // name source
    const nameContent = `${item.name_canonical} ${item.name_input ?? ""}`.trim();
    if (nameContent) {
      sources.push({ kind: "name", content: nameContent, source_ref: "name_canonical" });
    }

    // description source: prefer item_specs.description; fall back to notes.
    const spec = await ctx.runQuery(internal.item_embeddings.getItemSpec, {
      item_id: args.item_id,
    });
    const descContent =
      (spec?.description ?? "") + (item.notes ? `\n${item.notes}` : "");
    if (descContent.trim()) {
      sources.push({
        kind: "description",
        content: descContent.trim(),
        source_ref: spec ? "item_specs.description" : "items.notes",
      });
    }

    // image source: caption-based until Vertex multimodalembedding is wired.
    // Uses image_url as a stand-in caption (filename/path carries category
    // info on Hygglo). True multimodal lands in a follow-up phase.
    if (item.image_url) {
      const imgCaption = `Photo of ${item.name_canonical}: ${item.image_url}`;
      sources.push({
        kind: "image",
        content: imgCaption,
        source_ref: item.image_url,
      });
    }

    for (const src of sources) {
      const alreadyDone = await ctx.runQuery(internal.item_embeddings.hasEmbedding, {
        item_id: args.item_id,
        source_kind: src.kind,
      });
      if (alreadyDone) {
        skipped++;
        continue;
      }
      const vec = await client.embedContent(src.content);
      if (!vec) {
        skipped++;
        continue;
      }
      await ctx.runMutation(internal.item_embeddings.upsertEmbedding, {
        item_id: args.item_id,
        embedding: vec,
        embedding_model: EMBEDDING_MODEL,
        source_kind: src.kind,
        source_ref: src.source_ref,
      });
      generated++;
    }

    return { generated, skipped };
  },
});

/**
 * Side-table description lookup. Returns null when no spec exists.
 */
export const getItemSpec = internalQuery({
  args: { item_id: v.id("items") },
  handler: async (ctx, args) => {
    return await ctx.db
      .query("item_specs")
      .withIndex("by_item", (q) => q.eq("item_id", args.item_id))
      .first();
  },
});

/**
 * Semantic search via vectorIndex. Returns top-K nearest neighbours,
 * optionally filtered by source_kind. Vector search must run inside an
 * action (vectorSearch isn't available on the query ctx).
 */
export const searchSimilar = internalAction({
  args: {
    embedding: v.array(v.float64()),
    topK: v.number(),
    source_kind: v.optional(
      v.union(v.literal("name"), v.literal("description"), v.literal("image")),
    ),
  },
  handler: async (
    ctx,
    args,
  ): Promise<Array<{ _id: Id<"item_embeddings">; _score: number }>> => {
    if (args.embedding.length !== EMBEDDING_DIMENSIONS) {
      console.warn(
        `[item_embeddings.searchSimilar] embedding dim ${args.embedding.length} != ${EMBEDDING_DIMENSIONS}`,
      );
      return [];
    }
    const results = await ctx.vectorSearch("item_embeddings", "by_embedding", {
      vector: args.embedding,
      limit: Math.max(1, Math.min(args.topK, 256)),
      filter: args.source_kind
        ? (q) => q.eq("source_kind", args.source_kind!)
        : undefined,
    });
    return results.map((r) => ({ _id: r._id, _score: r._score }));
  },
});

/**
 * Chunked, idempotent backfill. Walks items table in `_creationTime`
 * order, embedding any rows whose (item_id, source_kind) isn't already
 * embedded with the current model. `chunkSize` caps items per chunk;
 * `maxChunks` caps total chunks per invocation so we stay under Convex
 * action budgets.
 *
 * Manual invoke (no cron). Re-invoke as needed — already-done rows are
 * skipped cheaply via the hasEmbedding query.
 */
export const backfillEmbeddings = internalAction({
  args: {
    chunkSize: v.optional(v.number()),
    maxChunks: v.optional(v.number()),
  },
  handler: async (
    ctx,
    args,
  ): Promise<{
    items_scanned: number;
    embeddings_generated: number;
    embeddings_skipped: number;
    chunks_run: number;
    api_key_present: boolean;
  }> => {
    const chunkSize = Math.max(1, Math.min(args.chunkSize ?? 25, 100));
    const maxChunks = Math.max(1, Math.min(args.maxChunks ?? 4, 50));

    const apiKeyPresent = !!process.env.GEMINI_API_KEY;
    if (!apiKeyPresent) {
      console.warn(
        "[item_embeddings.backfillEmbeddings] GEMINI_API_KEY missing — no-op",
      );
      return {
        items_scanned: 0,
        embeddings_generated: 0,
        embeddings_skipped: 0,
        chunks_run: 0,
        api_key_present: false,
      };
    }

    let cursor: number | undefined = undefined;
    let itemsScanned = 0;
    let generated = 0;
    let skipped = 0;
    let chunksRun = 0;

    for (let i = 0; i < maxChunks; i++) {
      const batch: Array<{
        _id: Id<"items">;
        _creationTime: number;
        name_canonical: string;
        name_input: string;
        image_url?: string;
      }> = await ctx.runQuery(internal.item_embeddings.listItemsForBackfill, {
        after_creation_time: cursor,
        limit: chunkSize,
      });
      if (batch.length === 0) break;
      chunksRun++;

      for (const row of batch) {
        const result = await ctx.runAction(
          internal.item_embeddings.generateEmbeddingsForItem,
          { item_id: row._id },
        );
        generated += result.generated;
        skipped += result.skipped;
        itemsScanned++;
        cursor = row._creationTime;
      }

      if (batch.length < chunkSize) break; // exhausted
    }

    return {
      items_scanned: itemsScanned,
      embeddings_generated: generated,
      embeddings_skipped: skipped,
      chunks_run: chunksRun,
      api_key_present: true,
    };
  },
});
