import { defineConfig } from "vitest/config";
import { fileURLToPath, URL } from "node:url";

/**
 * Minimal vitest config — Wave 1 unit tests only.
 *
 * Node environment (no jsdom, no Convex test runtime). Targets the
 * mastra/lib units that are pure TS + injectable stubs.
 *
 * CSS / PostCSS pipeline is disabled — the project's `postcss.config.mjs`
 * uses Tailwind v4's async plugin loader. Unit tests don't touch CSS,
 * so the unit test runner does not need the PostCSS pipeline.
 */
export default defineConfig({
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url)),
    },
  },
  css: { postcss: { plugins: [] } },
  test: {
    environment: "node",
    globals: false,
    include: [
      "convex/lib/item_technical_context.test.ts",
      "convex/lib/owner_setup.test.ts",
      "convex/lib/owner_authorization.test.ts",
      "convex/owner_functions.test.ts",
      "src/lib/convex-service.test.ts",
      "src/lib/convex-request-context.test.ts",
      "src/lib/convex-query-session.test.ts",
      "src/lib/owner-http-route.test.ts",
      "src/app/api/renter-bot-ab/route.test.ts",
      "src/app/api/push/renew/route.test.ts",
      "src/mastra/**/*.test.ts",
      "convex/lib/item_matcher.test.ts",
      "convex/lib/item_resolution.test.ts",
      "convex/lib/lens_set_resolution.test.ts",
      "convex/lib/renter_stock.test.ts",
      "convex/lib/stock_claims.test.ts",
      "convex/lib/catalogue_readiness.test.ts",
      "convex/lib/claim_date_scope.test.ts",
      "convex/lib/price_claims.test.ts",
      "convex/lib/required_mount_adapter.test.ts",
      "convex/lib/minimum_rental.test.ts",
      "src/lib/renter-price-evidence.test.ts",
      "src/lib/renter-pricing-preview.test.ts",
      "convex/settings.draft-epoch.test.ts",
      "convex/lib/listing_inventory.test.ts",
      "convex/lib/recommendation_basket.test.ts",
      "convex/lib/availability_basket.test.ts",
      "convex/lib/listing_media_conflict.test.ts",
      "convex/lib/verified_item_spec.test.ts",
      "convex/lib/renter_kit_evidence.test.ts",
      "convex/lib/kit_claims.test.ts",
      "convex/lib/draft_review.test.ts",
      "convex/lib/fulfillment_claims.test.ts",
      "convex/replyInbox.review.test.ts",
      "convex/lib/recommendation_kit.test.ts",
      "convex/seed/kit_source_repair.test.ts",
      "convex/lib/lens_requirements.test.ts",
      "convex/lib/camera_requirements.test.ts",
      "convex/lib/camera_mode_claims.test.ts",
      "convex/lib/camera_sensor_comparisons.test.ts",
      "convex/lib/push_registration.test.ts",
      "convex/notifications.push.test.ts",
      "src/lib/push-service-worker.test.ts",
      "convex/lib/lab_lifecycle.test.ts",
      "convex/lib/item_display_name.test.ts",
      "convex/lib/reservations/itemUnits.test.ts",
      "convex/lib/rental_stage.test.ts",
      "convex/lib/renter_booking_consent.test.ts",
      "convex/lib/renter_identity.test.ts",
      "src/lib/renter-tool-evidence.test.ts",
      "src/lib/renter-tool-scope.test.ts",
      "convex/lib/thread_messages.test.ts",
      "convex/lib/base_listing_identity.test.ts",
      "convex/lib/effectiveDates.test.ts",
      "convex/lib/item_name_match.test.ts",
      "convex/lib/platform_fallout.test.ts",
      "convex/lib/bundle_description_parse.test.ts",
      "convex/renter_bot_lab_order.test.ts",
      "convex/renter_bot_lab_order.atomic.test.ts",
      "convex/lib/renter_sent_proposal.test.ts",
      "convex/lib/renter_addition_acceptance.test.ts",
      "convex/lib/renter_replacement_acceptance.test.ts",
      "convex/lib/renter_date_acceptance.test.ts",
      "src/lib/renter-date-price-evidence.test.ts",
      "convex/lib/renter_removal_acceptance.test.ts",
      "convex/lib/amendment_confirmation.test.ts",
      "convex/renter_bot_lab_verification.test.ts",
      "convex/lib/hygglo_pricing.test.ts",
      "convex/lib/renter_bot_conversation_rubric.test.ts",
      "convex/lib/listing_equivalence.test.ts",
      "convex/lib/revenue_attribution.test.ts",
      "convex/lib/denial_classifier.test.ts",
      "convex/lib/availability.test.ts",
      "convex/lib/weekly_metrics_compute.test.ts",
      "convex/lib/capacity_gap.test.ts",
      "convex/lib/month_projection.test.ts",
      "convex/lib/conversation_funnel.test.ts",
      "convex/lib/double_booking.test.ts",
      "convex/lib/per_listing_merge.test.ts",
      "convex/lib/return_presence.test.ts",
      "convex/lib/message_reconciliation.test.ts",
      "convex/lib/imminent_handoffs.test.ts",
      "convex/lib/notification_events.test.ts",
      "convex/lib/telegram_convex.test.ts",
      "convex/lib/draft_listing_grounding.test.ts",
      "convex/lib/draft_guard.test.ts",
      "convex/lib/shadow_compare.test.ts",
      "src/lib/harvest-tool-prices.test.ts",
      "convex/lib/knowledge_search.test.ts",
      "convex/lib/channel_response_rates.test.ts",
      "convex/lib/poller_window.test.ts",
      "convex/lib/response_rate_alerts.test.ts",
      "convex/dashboard_insights.spec.ts",
      "convex/dashboard_chat.walle.spec.ts",
      "src/lib/dashboard/edit-mode-context.spec.ts",
      "src/trigger/catalog-sync.map.test.ts",
      "src/lib/hygglo-write.test.ts",
      "src/lib/hygglo/listings.test.ts",
      "src/lib/chat/dashboard-tools.schema.test.ts",
      "src/lib/renter-bot-policy.test.ts",
      "src/lib/renter-bot-output.test.ts",
      "convex/lib/renter_bot_rubric.test.ts",
      "src/lib/booking-time-transcript.test.ts",
      "src/lib/booking-time-extraction.test.ts",
      "src/lib/calendar-bar-geometry.test.ts",
      "src/lib/revenue/leo-takeover.test.ts",
      "src/lib/item-resolution.test.ts",
      "src/lib/quiet-hours.test.ts",
      "src/lib/pickup-hours.test.ts",
      "src/lib/hygglo-poll-backoff.test.ts",
      "src/lib/ai-models.chat-lanes.test.ts",
      "src/trigger/hygglo-ui-action.gate.test.ts",
      "src/hygglo-core/__tests__/competitor-aggregate.test.ts",
      "src/hygglo-core/__tests__/shape.test.ts",
      "src/hygglo-core/__tests__/poll.test.ts",
      "convex/migrations/backfill_inclusive_duration.test.ts",
    ],
    css: false,
  },
});
