/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as account_state from "../account_state.js";
import type * as accounts from "../accounts.js";
import type * as admin_backfill_weekly_metrics from "../admin_backfill_weekly_metrics.js";
import type * as admin_backfill_weekly_metrics_5b from "../admin_backfill_weekly_metrics_5b.js";
import type * as admin_bootstrap_pidindex from "../admin_bootstrap_pidindex.js";
import type * as admin_debug_steps from "../admin_debug_steps.js";
import type * as admin_fix_inventory_20260625 from "../admin_fix_inventory_20260625.js";
import type * as admin_item_attribution from "../admin_item_attribution.js";
import type * as admin_migrate from "../admin_migrate.js";
import type * as admin_reclassify from "../admin_reclassify.js";
import type * as admin_reset_account_state from "../admin_reset_account_state.js";
import type * as ai_decisions from "../ai_decisions.js";
import type * as ai_insights from "../ai_insights.js";
import type * as archive_to_r2 from "../archive_to_r2.js";
import type * as archive_to_r2_helpers from "../archive_to_r2_helpers.js";
import type * as audit_capacity_gap_diagnostic from "../audit_capacity_gap_diagnostic.js";
import type * as audit_data_quality from "../audit_data_quality.js";
import type * as audit_listings from "../audit_listings.js";
import type * as audit_listings_data from "../audit_listings_data.js";
import type * as audit_qty_drift from "../audit_qty_drift.js";
import type * as audit_qty_drift_data from "../audit_qty_drift_data.js";
import type * as audit_reclassification from "../audit_reclassification.js";
import type * as audit_snapshot from "../audit_snapshot.js";
import type * as audit_thread_join from "../audit_thread_join.js";
import type * as backfill_blackmagic_descriptions from "../backfill_blackmagic_descriptions.js";
import type * as backfill_blackmagic_queries from "../backfill_blackmagic_queries.js";
import type * as bundles from "../bundles.js";
import type * as bundles_seed from "../bundles_seed.js";
import type * as calendar from "../calendar.js";
import type * as calendar_apple from "../calendar_apple.js";
import type * as calendar_apple_db from "../calendar_apple_db.js";
import type * as canned_responses from "../canned_responses.js";
import type * as channel_response_rates from "../channel_response_rates.js";
import type * as competitor_intel from "../competitor_intel.js";
import type * as conflict_dismissals from "../conflict_dismissals.js";
import type * as crons from "../crons.js";
import type * as dashboard from "../dashboard.js";
import type * as dashboardLayout from "../dashboardLayout.js";
import type * as dashboard_attribution_preview from "../dashboard_attribution_preview.js";
import type * as dashboard_chat from "../dashboard_chat.js";
import type * as dashboard_insights from "../dashboard_insights.js";
import type * as dashboard_invariants from "../dashboard_invariants.js";
import type * as demand from "../demand.js";
import type * as demand_loss from "../demand_loss.js";
import type * as denial_canonicalizer_queries from "../denial_canonicalizer_queries.js";
import type * as denial_records from "../denial_records.js";
import type * as denial_resolutions from "../denial_resolutions.js";
import type * as denial_resolver from "../denial_resolver.js";
import type * as diag_bundle_parse from "../diag_bundle_parse.js";
import type * as diag_kit_contents from "../diag_kit_contents.js";
import type * as diag_lab_runs from "../diag_lab_runs.js";
import type * as diag_twin_gaps from "../diag_twin_gaps.js";
import type * as draft_learning from "../draft_learning.js";
import type * as draft_learning_actions from "../draft_learning_actions.js";
import type * as extract_booking_times from "../extract_booking_times.js";
import type * as extract_booking_times_q from "../extract_booking_times_q.js";
import type * as feature_flags from "../feature_flags.js";
import type * as grounding_audit from "../grounding_audit.js";
import type * as health from "../health.js";
import type * as historical_revenue from "../historical_revenue.js";
import type * as http from "../http.js";
import type * as hygglo from "../hygglo.js";
import type * as hygglo_presence from "../hygglo_presence.js";
import type * as hygglo_products from "../hygglo_products.js";
import type * as inquiry_context from "../inquiry_context.js";
import type * as insurance_claims from "../insurance_claims.js";
import type * as intel from "../intel.js";
import type * as investigate_autodesc from "../investigate_autodesc.js";
import type * as investigate_diogo_desc from "../investigate_diogo_desc.js";
import type * as investigate_integrity from "../investigate_integrity.js";
import type * as investigate_overrides from "../investigate_overrides.js";
import type * as item_resolver from "../item_resolver.js";
import type * as item_resolver_queries from "../item_resolver_queries.js";
import type * as items from "../items.js";
import type * as knowledge from "../knowledge.js";
import type * as lib_ai_attribution from "../lib/ai_attribution.js";
import type * as lib_availability from "../lib/availability.js";
import type * as lib_bundle_description_parse from "../lib/bundle_description_parse.js";
import type * as lib_capacity_gap from "../lib/capacity_gap.js";
import type * as lib_co_occurrence from "../lib/co_occurrence.js";
import type * as lib_customer_metrics from "../lib/customer_metrics.js";
import type * as lib_delivery_weight from "../lib/delivery_weight.js";
import type * as lib_denial_classifier from "../lib/denial_classifier.js";
import type * as lib_double_booking from "../lib/double_booking.js";
import type * as lib_draft_guard from "../lib/draft_guard.js";
import type * as lib_draft_listing_grounding from "../lib/draft_listing_grounding.js";
import type * as lib_draft_playbook from "../lib/draft_playbook.js";
import type * as lib_effectiveDates from "../lib/effectiveDates.js";
import type * as lib_feature_flags_helper from "../lib/feature_flags_helper.js";
import type * as lib_gatedGenerate from "../lib/gatedGenerate.js";
import type * as lib_imageResolution from "../lib/imageResolution.js";
import type * as lib_imminent_handoffs from "../lib/imminent_handoffs.js";
import type * as lib_inventory_categories from "../lib/inventory_categories.js";
import type * as lib_item_matcher from "../lib/item_matcher.js";
import type * as lib_item_name_match from "../lib/item_name_match.js";
import type * as lib_item_taxonomy from "../lib/item_taxonomy.js";
import type * as lib_knowledge_search from "../lib/knowledge_search.js";
import type * as lib_listing_equivalence from "../lib/listing_equivalence.js";
import type * as lib_listing_photo_reference from "../lib/listing_photo_reference.js";
import type * as lib_message_reconciliation from "../lib/message_reconciliation.js";
import type * as lib_missed_revenue from "../lib/missed_revenue.js";
import type * as lib_notification_events from "../lib/notification_events.js";
import type * as lib_poller_window from "../lib/poller_window.js";
import type * as lib_quiet_hours from "../lib/quiet_hours.js";
import type * as lib_rental_volume from "../lib/rental_volume.js";
import type * as lib_renterLookup from "../lib/renterLookup.js";
import type * as lib_renter_bot_conversation_rubric from "../lib/renter_bot_conversation_rubric.js";
import type * as lib_renter_bot_filters from "../lib/renter_bot_filters.js";
import type * as lib_renter_bot_filters_supplemental from "../lib/renter_bot_filters_supplemental.js";
import type * as lib_renter_bot_intents from "../lib/renter_bot_intents.js";
import type * as lib_renter_bot_negotiation from "../lib/renter_bot_negotiation.js";
import type * as lib_renter_bot_rubric from "../lib/renter_bot_rubric.js";
import type * as lib_renter_bot_tone_scorer from "../lib/renter_bot_tone_scorer.js";
import type * as lib_renter_dna from "../lib/renter_dna.js";
import type * as lib_renters from "../lib/renters.js";
import type * as lib_reservations_accounts from "../lib/reservations/accounts.js";
import type * as lib_reservations_hyggloTiles from "../lib/reservations/hyggloTiles.js";
import type * as lib_reservations_itemUnits from "../lib/reservations/itemUnits.js";
import type * as lib_reservations_monthRevenue from "../lib/reservations/monthRevenue.js";
import type * as lib_reservations_predicates from "../lib/reservations/predicates.js";
import type * as lib_reservations_views from "../lib/reservations/views.js";
import type * as lib_response_rate_alerts from "../lib/response_rate_alerts.js";
import type * as lib_return_discounts from "../lib/return_discounts.js";
import type * as lib_return_messages from "../lib/return_messages.js";
import type * as lib_return_presence from "../lib/return_presence.js";
import type * as lib_revenue_attribution from "../lib/revenue_attribution.js";
import type * as lib_telegram_convex from "../lib/telegram_convex.js";
import type * as lib_weekly_metrics_compute from "../lib/weekly_metrics_compute.js";
import type * as lib_widget_mv from "../lib/widget_mv.js";
import type * as listing_cache from "../listing_cache.js";
import type * as listing_equivalence_admin from "../listing_equivalence_admin.js";
import type * as listing_images from "../listing_images.js";
import type * as listing_info_pool from "../listing_info_pool.js";
import type * as listing_overrides from "../listing_overrides.js";
import type * as listing_price_admin from "../listing_price_admin.js";
import type * as listing_resolver from "../listing_resolver.js";
import type * as listing_resolver_data from "../listing_resolver_data.js";
import type * as listing_short_names from "../listing_short_names.js";
import type * as listing_short_names_actions from "../listing_short_names_actions.js";
import type * as locations from "../locations.js";
import type * as lost_revenue from "../lost_revenue.js";
import type * as market_search from "../market_search.js";
import type * as market_search_cache from "../market_search_cache.js";
import type * as memories from "../memories.js";
import type * as model_upgrade_scans from "../model_upgrade_scans.js";
import type * as mv__helpers from "../mv/_helpers.js";
import type * as mv_ai_insights from "../mv/ai_insights.js";
import type * as mv_calendar from "../mv/calendar.js";
import type * as mv_churn_risk from "../mv/churn_risk.js";
import type * as mv_constants from "../mv/constants.js";
import type * as mv_conversion_funnel from "../mv/conversion_funnel.js";
import type * as mv_daily_briefing from "../mv/daily_briefing.js";
import type * as mv_due_returns from "../mv/due_returns.js";
import type * as mv_earnings_by_period from "../mv/earnings_by_period.js";
import type * as mv_investment_scorecard from "../mv/investment_scorecard.js";
import type * as mv_item_roi_rankings from "../mv/item_roi_rankings.js";
import type * as mv_lifetime_revenue from "../mv/lifetime_revenue.js";
import type * as mv_master from "../mv/master.js";
import type * as mv_missed_denied_by_category from "../mv/missed_denied_by_category.js";
import type * as mv_missed_denied_compute from "../mv/missed_denied_compute.js";
import type * as mv_missed_revenue from "../mv/missed_revenue.js";
import type * as mv_purchase_signals from "../mv/purchase_signals.js";
import type * as mv_refresh_dispatch from "../mv/refresh_dispatch.js";
import type * as mv_rental_volume_by_category from "../mv/rental_volume_by_category.js";
import type * as mv_rental_volume_kind_breakdown from "../mv/rental_volume_kind_breakdown.js";
import type * as mv_reply_queue from "../mv/reply_queue.js";
import type * as mv_stats_drawer from "../mv/stats_drawer.js";
import type * as mv_top_earners from "../mv/top_earners.js";
import type * as mv_upcoming_returns from "../mv/upcoming_returns.js";
import type * as mv_utilization from "../mv/utilization.js";
import type * as mv_walle_signals from "../mv/walle_signals.js";
import type * as mv_widgets from "../mv/widgets.js";
import type * as mv_refresh_locks from "../mv_refresh_locks.js";
import type * as notifications from "../notifications.js";
import type * as notifications_send from "../notifications_send.js";
import type * as online_listings from "../online_listings.js";
import type * as online_listings_actions from "../online_listings_actions.js";
import type * as order_edit from "../order_edit.js";
import type * as order_step_semantics from "../order_step_semantics.js";
import type * as poller_health from "../poller_health.js";
import type * as ported_listings from "../ported_listings.js";
import type * as pricing_catalog from "../pricing_catalog.js";
import type * as propose_bmpcc_mapping from "../propose_bmpcc_mapping.js";
import type * as propose_bundle_mapping from "../propose_bundle_mapping.js";
import type * as rate_limit_config from "../rate_limit_config.js";
import type * as renter_bot_batch from "../renter_bot_batch.js";
import type * as renter_bot_drafts from "../renter_bot_drafts.js";
import type * as renter_bot_fixture_import from "../renter_bot_fixture_import.js";
import type * as renter_bot_fixture_import_db from "../renter_bot_fixture_import_db.js";
import type * as renter_bot_fixture_seed_v1_scenarios from "../renter_bot_fixture_seed_v1_scenarios.js";
import type * as renter_bot_harness from "../renter_bot_harness.js";
import type * as renter_bot_lab_actions from "../renter_bot_lab_actions.js";
import type * as renter_bot_probe from "../renter_bot_probe.js";
import type * as renter_bot_seed from "../renter_bot_seed.js";
import type * as renter_bot_tools from "../renter_bot_tools.js";
import type * as renter_reviews from "../renter_reviews.js";
import type * as renter_trust from "../renter_trust.js";
import type * as renters from "../renters.js";
import type * as renters_admin from "../renters_admin.js";
import type * as replyInbox from "../replyInbox.js";
import type * as replyInbox_actions from "../replyInbox_actions.js";
import type * as reservation_vision from "../reservation_vision.js";
import type * as reservations from "../reservations.js";
import type * as returns_autoclose from "../returns_autoclose.js";
import type * as returns_reconcile from "../returns_reconcile.js";
import type * as revenue from "../revenue.js";
import type * as rules from "../rules.js";
import type * as seed_account_hubs from "../seed/account_hubs.js";
import type * as seed_data from "../seed/data.js";
import type * as seed_diogo_profile from "../seed/diogo_profile.js";
import type * as seed_hard_truths from "../seed/hard_truths.js";
import type * as seed_inventory from "../seed/inventory.js";
import type * as seed_renter_bot_memories from "../seed/renter_bot_memories.js";
import type * as seed_renter_bot_rules from "../seed/renter_bot_rules.js";
import type * as seed_settings from "../seed/settings.js";
import type * as settings from "../settings.js";
import type * as sync_account_profiles from "../sync_account_profiles.js";
import type * as sync_dbcinema_web from "../sync_dbcinema_web.js";
import type * as sync_state from "../sync_state.js";
import type * as tax from "../tax.js";
import type * as telegram_inbound from "../telegram_inbound.js";
import type * as todos from "../todos.js";
import type * as vacation from "../vacation.js";
import type * as walle_inventory from "../walle_inventory.js";
import type * as walle_ratelimits from "../walle_ratelimits.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  account_state: typeof account_state;
  accounts: typeof accounts;
  admin_backfill_weekly_metrics: typeof admin_backfill_weekly_metrics;
  admin_backfill_weekly_metrics_5b: typeof admin_backfill_weekly_metrics_5b;
  admin_bootstrap_pidindex: typeof admin_bootstrap_pidindex;
  admin_debug_steps: typeof admin_debug_steps;
  admin_fix_inventory_20260625: typeof admin_fix_inventory_20260625;
  admin_item_attribution: typeof admin_item_attribution;
  admin_migrate: typeof admin_migrate;
  admin_reclassify: typeof admin_reclassify;
  admin_reset_account_state: typeof admin_reset_account_state;
  ai_decisions: typeof ai_decisions;
  ai_insights: typeof ai_insights;
  archive_to_r2: typeof archive_to_r2;
  archive_to_r2_helpers: typeof archive_to_r2_helpers;
  audit_capacity_gap_diagnostic: typeof audit_capacity_gap_diagnostic;
  audit_data_quality: typeof audit_data_quality;
  audit_listings: typeof audit_listings;
  audit_listings_data: typeof audit_listings_data;
  audit_qty_drift: typeof audit_qty_drift;
  audit_qty_drift_data: typeof audit_qty_drift_data;
  audit_reclassification: typeof audit_reclassification;
  audit_snapshot: typeof audit_snapshot;
  audit_thread_join: typeof audit_thread_join;
  backfill_blackmagic_descriptions: typeof backfill_blackmagic_descriptions;
  backfill_blackmagic_queries: typeof backfill_blackmagic_queries;
  bundles: typeof bundles;
  bundles_seed: typeof bundles_seed;
  calendar: typeof calendar;
  calendar_apple: typeof calendar_apple;
  calendar_apple_db: typeof calendar_apple_db;
  canned_responses: typeof canned_responses;
  channel_response_rates: typeof channel_response_rates;
  competitor_intel: typeof competitor_intel;
  conflict_dismissals: typeof conflict_dismissals;
  crons: typeof crons;
  dashboard: typeof dashboard;
  dashboardLayout: typeof dashboardLayout;
  dashboard_attribution_preview: typeof dashboard_attribution_preview;
  dashboard_chat: typeof dashboard_chat;
  dashboard_insights: typeof dashboard_insights;
  dashboard_invariants: typeof dashboard_invariants;
  demand: typeof demand;
  demand_loss: typeof demand_loss;
  denial_canonicalizer_queries: typeof denial_canonicalizer_queries;
  denial_records: typeof denial_records;
  denial_resolutions: typeof denial_resolutions;
  denial_resolver: typeof denial_resolver;
  diag_bundle_parse: typeof diag_bundle_parse;
  diag_kit_contents: typeof diag_kit_contents;
  diag_lab_runs: typeof diag_lab_runs;
  diag_twin_gaps: typeof diag_twin_gaps;
  draft_learning: typeof draft_learning;
  draft_learning_actions: typeof draft_learning_actions;
  extract_booking_times: typeof extract_booking_times;
  extract_booking_times_q: typeof extract_booking_times_q;
  feature_flags: typeof feature_flags;
  grounding_audit: typeof grounding_audit;
  health: typeof health;
  historical_revenue: typeof historical_revenue;
  http: typeof http;
  hygglo: typeof hygglo;
  hygglo_presence: typeof hygglo_presence;
  hygglo_products: typeof hygglo_products;
  inquiry_context: typeof inquiry_context;
  insurance_claims: typeof insurance_claims;
  intel: typeof intel;
  investigate_autodesc: typeof investigate_autodesc;
  investigate_diogo_desc: typeof investigate_diogo_desc;
  investigate_integrity: typeof investigate_integrity;
  investigate_overrides: typeof investigate_overrides;
  item_resolver: typeof item_resolver;
  item_resolver_queries: typeof item_resolver_queries;
  items: typeof items;
  knowledge: typeof knowledge;
  "lib/ai_attribution": typeof lib_ai_attribution;
  "lib/availability": typeof lib_availability;
  "lib/bundle_description_parse": typeof lib_bundle_description_parse;
  "lib/capacity_gap": typeof lib_capacity_gap;
  "lib/co_occurrence": typeof lib_co_occurrence;
  "lib/customer_metrics": typeof lib_customer_metrics;
  "lib/delivery_weight": typeof lib_delivery_weight;
  "lib/denial_classifier": typeof lib_denial_classifier;
  "lib/double_booking": typeof lib_double_booking;
  "lib/draft_guard": typeof lib_draft_guard;
  "lib/draft_listing_grounding": typeof lib_draft_listing_grounding;
  "lib/draft_playbook": typeof lib_draft_playbook;
  "lib/effectiveDates": typeof lib_effectiveDates;
  "lib/feature_flags_helper": typeof lib_feature_flags_helper;
  "lib/gatedGenerate": typeof lib_gatedGenerate;
  "lib/imageResolution": typeof lib_imageResolution;
  "lib/imminent_handoffs": typeof lib_imminent_handoffs;
  "lib/inventory_categories": typeof lib_inventory_categories;
  "lib/item_matcher": typeof lib_item_matcher;
  "lib/item_name_match": typeof lib_item_name_match;
  "lib/item_taxonomy": typeof lib_item_taxonomy;
  "lib/knowledge_search": typeof lib_knowledge_search;
  "lib/listing_equivalence": typeof lib_listing_equivalence;
  "lib/listing_photo_reference": typeof lib_listing_photo_reference;
  "lib/message_reconciliation": typeof lib_message_reconciliation;
  "lib/missed_revenue": typeof lib_missed_revenue;
  "lib/notification_events": typeof lib_notification_events;
  "lib/poller_window": typeof lib_poller_window;
  "lib/quiet_hours": typeof lib_quiet_hours;
  "lib/rental_volume": typeof lib_rental_volume;
  "lib/renterLookup": typeof lib_renterLookup;
  "lib/renter_bot_conversation_rubric": typeof lib_renter_bot_conversation_rubric;
  "lib/renter_bot_filters": typeof lib_renter_bot_filters;
  "lib/renter_bot_filters_supplemental": typeof lib_renter_bot_filters_supplemental;
  "lib/renter_bot_intents": typeof lib_renter_bot_intents;
  "lib/renter_bot_negotiation": typeof lib_renter_bot_negotiation;
  "lib/renter_bot_rubric": typeof lib_renter_bot_rubric;
  "lib/renter_bot_tone_scorer": typeof lib_renter_bot_tone_scorer;
  "lib/renter_dna": typeof lib_renter_dna;
  "lib/renters": typeof lib_renters;
  "lib/reservations/accounts": typeof lib_reservations_accounts;
  "lib/reservations/hyggloTiles": typeof lib_reservations_hyggloTiles;
  "lib/reservations/itemUnits": typeof lib_reservations_itemUnits;
  "lib/reservations/monthRevenue": typeof lib_reservations_monthRevenue;
  "lib/reservations/predicates": typeof lib_reservations_predicates;
  "lib/reservations/views": typeof lib_reservations_views;
  "lib/response_rate_alerts": typeof lib_response_rate_alerts;
  "lib/return_discounts": typeof lib_return_discounts;
  "lib/return_messages": typeof lib_return_messages;
  "lib/return_presence": typeof lib_return_presence;
  "lib/revenue_attribution": typeof lib_revenue_attribution;
  "lib/telegram_convex": typeof lib_telegram_convex;
  "lib/weekly_metrics_compute": typeof lib_weekly_metrics_compute;
  "lib/widget_mv": typeof lib_widget_mv;
  listing_cache: typeof listing_cache;
  listing_equivalence_admin: typeof listing_equivalence_admin;
  listing_images: typeof listing_images;
  listing_info_pool: typeof listing_info_pool;
  listing_overrides: typeof listing_overrides;
  listing_price_admin: typeof listing_price_admin;
  listing_resolver: typeof listing_resolver;
  listing_resolver_data: typeof listing_resolver_data;
  listing_short_names: typeof listing_short_names;
  listing_short_names_actions: typeof listing_short_names_actions;
  locations: typeof locations;
  lost_revenue: typeof lost_revenue;
  market_search: typeof market_search;
  market_search_cache: typeof market_search_cache;
  memories: typeof memories;
  model_upgrade_scans: typeof model_upgrade_scans;
  "mv/_helpers": typeof mv__helpers;
  "mv/ai_insights": typeof mv_ai_insights;
  "mv/calendar": typeof mv_calendar;
  "mv/churn_risk": typeof mv_churn_risk;
  "mv/constants": typeof mv_constants;
  "mv/conversion_funnel": typeof mv_conversion_funnel;
  "mv/daily_briefing": typeof mv_daily_briefing;
  "mv/due_returns": typeof mv_due_returns;
  "mv/earnings_by_period": typeof mv_earnings_by_period;
  "mv/investment_scorecard": typeof mv_investment_scorecard;
  "mv/item_roi_rankings": typeof mv_item_roi_rankings;
  "mv/lifetime_revenue": typeof mv_lifetime_revenue;
  "mv/master": typeof mv_master;
  "mv/missed_denied_by_category": typeof mv_missed_denied_by_category;
  "mv/missed_denied_compute": typeof mv_missed_denied_compute;
  "mv/missed_revenue": typeof mv_missed_revenue;
  "mv/purchase_signals": typeof mv_purchase_signals;
  "mv/refresh_dispatch": typeof mv_refresh_dispatch;
  "mv/rental_volume_by_category": typeof mv_rental_volume_by_category;
  "mv/rental_volume_kind_breakdown": typeof mv_rental_volume_kind_breakdown;
  "mv/reply_queue": typeof mv_reply_queue;
  "mv/stats_drawer": typeof mv_stats_drawer;
  "mv/top_earners": typeof mv_top_earners;
  "mv/upcoming_returns": typeof mv_upcoming_returns;
  "mv/utilization": typeof mv_utilization;
  "mv/walle_signals": typeof mv_walle_signals;
  "mv/widgets": typeof mv_widgets;
  mv_refresh_locks: typeof mv_refresh_locks;
  notifications: typeof notifications;
  notifications_send: typeof notifications_send;
  online_listings: typeof online_listings;
  online_listings_actions: typeof online_listings_actions;
  order_edit: typeof order_edit;
  order_step_semantics: typeof order_step_semantics;
  poller_health: typeof poller_health;
  ported_listings: typeof ported_listings;
  pricing_catalog: typeof pricing_catalog;
  propose_bmpcc_mapping: typeof propose_bmpcc_mapping;
  propose_bundle_mapping: typeof propose_bundle_mapping;
  rate_limit_config: typeof rate_limit_config;
  renter_bot_batch: typeof renter_bot_batch;
  renter_bot_drafts: typeof renter_bot_drafts;
  renter_bot_fixture_import: typeof renter_bot_fixture_import;
  renter_bot_fixture_import_db: typeof renter_bot_fixture_import_db;
  renter_bot_fixture_seed_v1_scenarios: typeof renter_bot_fixture_seed_v1_scenarios;
  renter_bot_harness: typeof renter_bot_harness;
  renter_bot_lab_actions: typeof renter_bot_lab_actions;
  renter_bot_probe: typeof renter_bot_probe;
  renter_bot_seed: typeof renter_bot_seed;
  renter_bot_tools: typeof renter_bot_tools;
  renter_reviews: typeof renter_reviews;
  renter_trust: typeof renter_trust;
  renters: typeof renters;
  renters_admin: typeof renters_admin;
  replyInbox: typeof replyInbox;
  replyInbox_actions: typeof replyInbox_actions;
  reservation_vision: typeof reservation_vision;
  reservations: typeof reservations;
  returns_autoclose: typeof returns_autoclose;
  returns_reconcile: typeof returns_reconcile;
  revenue: typeof revenue;
  rules: typeof rules;
  "seed/account_hubs": typeof seed_account_hubs;
  "seed/data": typeof seed_data;
  "seed/diogo_profile": typeof seed_diogo_profile;
  "seed/hard_truths": typeof seed_hard_truths;
  "seed/inventory": typeof seed_inventory;
  "seed/renter_bot_memories": typeof seed_renter_bot_memories;
  "seed/renter_bot_rules": typeof seed_renter_bot_rules;
  "seed/settings": typeof seed_settings;
  settings: typeof settings;
  sync_account_profiles: typeof sync_account_profiles;
  sync_dbcinema_web: typeof sync_dbcinema_web;
  sync_state: typeof sync_state;
  tax: typeof tax;
  telegram_inbound: typeof telegram_inbound;
  todos: typeof todos;
  vacation: typeof vacation;
  walle_inventory: typeof walle_inventory;
  walle_ratelimits: typeof walle_ratelimits;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  rateLimiter: import("@convex-dev/rate-limiter/_generated/component.js").ComponentApi<"rateLimiter">;
};
