import {describe,it,expect} from "vitest";
import {acceptsReplacement,requiresReplacementTransaction,type ReplacementAcceptanceQuote} from "./renter_replacement_acceptance";
import {replacementProposalsFromEvidence,type SentReplacementProposal} from "./renter_replacement_proposal";
const old={product_id:1163215,name:"TTArtisan 11mm f2.8",qty:1,line_total_gbp:42},next={product_id:1115113,name:"Sony GM 16-35mm f2.8",qty:1,line_total_gbp:40};
const q:ReplacementAcceptanceQuote={context_key:"base",epoch:109,physical_identity_key:"new-physical",base_physical_identity_key:"old-physical",start_date:"2026-10-20",end_date:"2026-10-21",total_gbp:40,base_total_gbp:42,added:[next],removed:[old]};
const record:SentReplacementProposal={context_key:q.context_key,epoch:q.epoch,physical_identity_key:q.physical_identity_key,base_physical_identity_key:q.base_physical_identity_key,quoted_for_message_id:"previous",items:[{product_id:next.product_id,qty:1}],removed_listings:[{product_id:old.product_id,qty:1}],base_items:[{name:old.name,quantity:1}],added_items:[{name:next.name,quantity:1}],removed_items:[{name:old.name,quantity:1}],start_date:q.start_date,end_date:q.end_date,total_gbp:40,base_total_gbp:42};
const owner={body_text:"We can swap the TTArtisan 11mm f2.8 for Sony GM 16-35mm f2.8 for 20–21 October. Your updated booking total would be £40. Shall I make that swap?",quoted_replacements:[record]};
describe("Native replacement consent",()=>{
 it("accepts an unchanged transmitted offer without asking twice",()=>{for(const text of ["Yes","Yes please","Please go ahead","Go ahead and make the swap","Please swap TTArtisan 11mm f2.8 for Sony GM 16-35mm f2.8"])expect(acceptsReplacement(text,q,owner),text).toBe(true);});
 it("recognizes the captured prime shorthand against a complete physical lens identity",()=>{
  const full={...q,removed:[{...old,name:"TTArtisan 11mm f2.8 Fisheye (Sony E)"}]};
  expect(acceptsReplacement("Yes please",full,owner)).toBe(true);
 });
 it("accepts an exact directional request at the Native full price",()=>expect(acceptsReplacement("Please replace TTArtisan 11mm f2.8 with Sony GM 16-35mm f2.8 for £40 total.",q)).toBe(true));
 it("checks a saving against the Native delta while retaining full-total consent",()=>{
  const direction="Please swap TTArtisan 11mm f2.8 for Sony GM 16-35mm f2.8 for £40 total, a saving of £2.";
  expect(acceptsReplacement(direction,q)).toBe(true);
  for(const changed of [direction.replace("£2","£3"),direction.replace("saving","discount"),direction.replace("saving","refund"),direction.replace("a saving of £2","£2 extra"),direction.replace("£40 total, ","")])expect(acceptsReplacement(changed,q),changed).toBe(false);
  expect(acceptsReplacement(direction.replace("a saving of £2","£3 extra").replace("£40 total","£45 total"),{...q,total_gbp:45,added:[{...next,line_total_gbp:45}]})).toBe(true);
 });
 it("does not accept yes or an unpriced direction without a transmitted quote",()=>{expect(acceptsReplacement("yes",q)).toBe(false);expect(acceptsReplacement("please swap TTArtisan 11mm f2.8 for Sony GM 16-35mm f2.8",q)).toBe(false);});
 it("keeps the removal and addition directions and quantities exact",()=>{for(const text of ["Please swap Sony GM 16-35mm f2.8 for TTArtisan 11mm f2.8 for £40 total.","Please replace TTArtisan 11mm f2.8 with two Sony GM 16-35mm f2.8 for £40 total.","Please swap two TTArtisan 11mm f2.8 for Sony GM 16-35mm f2.8 for £40 total.","Please swap TTArtisan 50mm f2 for Sony GM 16-35mm f2.8 for £40 total.","Please swap TTArtisan 11mm f2.8 for Sony GM 16-35mm f2.8 or Sony 24-70mm for £40 total."])expect(acceptsReplacement(text,q,owner),text).toBe(false);});
 it("rejects changed basket mappings, dates, prices, epoch, context and selections",()=>{for(const changed of [{...q,physical_identity_key:"changed"},{...q,base_physical_identity_key:"changed"},{...q,start_date:"2026-10-22"},{...q,total_gbp:41},{...q,base_total_gbp:43},{...q,epoch:110},{...q,context_key:"changed"},{...q,added:[{...next,product_id:99}]},{...q,removed:[{...old,qty:2}]}])expect(acceptsReplacement("yes",changed,owner)).toBe(false);});
 it("requires an actual offered swap, names and full price rather than archived evidence alone",()=>{for(const body_text of ["I'll check those items.","Sony GM 16-35mm f2.8 is £40.",owner.body_text.replace("£40","£42"),owner.body_text.replace("Sony GM 16-35mm f2.8","Sony 24-70mm"),owner.body_text+" Or we could offer another option."])expect(acceptsReplacement("yes",q,{...owner,body_text})).toBe(false);expect(acceptsReplacement("yes",q,{...owner,quoted_replacements:[record,record]})).toBe(false);});
 it("rejects questions, conditions, quoted instructions, negation and changed terms",()=>{for(const text of ["How much?","Maybe yes","Yes but not yet","Yes if it's available","Do not swap it","He said \"please swap TTArtisan 11mm f2.8 for Sony GM 16-35mm f2.8 for £40 total\"","Please swap TTArtisan 11mm f2.8 for Sony GM 16-35mm f2.8 for £39 total.","Please swap TTArtisan 11mm f2.8 for Sony GM 16-35mm f2.8 for £40 total on 22–23 October.","Please swap TTArtisan 11mm f2.8 for Sony GM 16-35mm f2.8 for £40/day."])expect(acceptsReplacement(text,q,owner),text).toBe(false);});
 it("prevents independent legacy edits for the same swap or reference",()=>{expect(requiresReplacementTransaction("Please swap TTArtisan for Sony")).toBe(true);expect(requiresReplacementTransaction("Yes",owner)).toBe(true);expect(requiresReplacementTransaction("Please add Sony FX3",owner)).toBe(false);});
 it("archives only bounded Native selections with both physical identities",()=>{
  const price={names:[],kind:"basket" as const,source:"native_lab_proposal",call_id:"actual",start_date:q.start_date,end_date:q.end_date,total_gbp:40,proposal:{base_items:record.base_items,added_items:record.added_items,removed_items:record.removed_items,physical_identity_key:q.physical_identity_key,base_physical_identity_key:q.base_physical_identity_key,base_total_gbp:42,added_listings:[{product_id:next.product_id,quantity:1}],removed_listings:[{product_id:old.product_id,quantity:1}]}};
  expect(replacementProposalsFromEvidence([price],{context_key:"base",epoch:109,message_id:"previous"})).toEqual([record]);
  for(const proposal of [{...price.proposal,base_physical_identity_key:undefined},{...price.proposal,removed_listings:undefined},{...price.proposal,base_total_gbp:NaN},{...price.proposal,added_listings:[{product_id:0,quantity:1}]},{...price.proposal,removed_listings:[{product_id:old.product_id,quantity:21}]}])expect(replacementProposalsFromEvidence([{...price,proposal}],{context_key:"base",epoch:109,message_id:"previous"})).toEqual([]);
 });
});
