/** Exact models reviewed against their manufacturer pages on 2026-10-01. Retail-box contents are not rental-kit evidence. */
export const REVIEWED_CAMERA_SPECS = [
 { name: "Sony A7 II", model: "ILCE-7M2", url: "https://www.sony.co.uk/electronics/support/e-mount-body-ilce-7-series/ilce-7m2/specifications", description: "Sony A7 II (ILCE-7M2): 24.3MP full-frame sensor and Sony E mount. Internal video recording up to 1920x1080 at 60p; this is not a 4K-recording body. Uses SD media and NP-FW50 batteries." },
 { name: "Sony A7 III", model: "ILCE-7M3", url: "https://www.sony.co.uk/electronics/support/e-mount-body-ilce7-series/ilce-7m3/specifications", description: "Sony A7 III (ILCE-7M3): approximately 24.2MP effective full-frame Exmor R CMOS sensor; Sony E mount. Records 4K up to 30p and Full HD up to 120p. Recording mode, region and frame rate affect available formats." },
 { name: "Sony FX3", model: "ILME-FX3", url: "https://www.sony.co.uk/electronics/support/camcorders-and-video-cameras-interchangeable-lens-camcorders/ilme-fx3/specifications", description: "Sony FX3 (ILME-FX3): full-frame Exmor R CMOS sensor, approximately 12.1MP effective for still images. Sony E mount. Two CFexpress Type A/SD memory-card slots. NP-FZ100 battery. Recording formats and supported media depend on mode and firmware." },
 { name: "GoPro 12 Hero", model: "HERO12 Black", url: "https://gopro.com/en/gb/shop/cameras/hero12-black/CHDHX-121-master.html", description: "GoPro HERO12 Black: 27MP photos; 5.3K video up to 60fps, 4K up to 120fps and 2.7K up to 240fps in the supported aspect ratios. HyperSmooth 6.0 stabilization. Uses microSD media. Lens is fixed, not interchangeable." },
 { name: "DJI Osmo Action Pro 5", model: "Osmo Action 5 Pro", url: "https://www.dji.com/osmo-action-5-pro/specs", description: "DJI Osmo Action 5 Pro: 1/1.3-inch CMOS sensor, approximately 40MP photos, 4K recording up to 120fps; fixed lens. Supports microSD up to 1TB. Manufacturer waterproof rating is 20m without a case only under its sealing/use conditions; this does not establish rental permission for underwater use." },
 { name: "BMPCC 6K Pro", model: "Blackmagic Pocket Cinema Camera 6K Pro", url: "https://www.blackmagicdesign.com/products/blackmagicpocketcinemacamera/techspecs", description: "Blackmagic Pocket Cinema Camera 6K Pro: 6144x3456 Super 35 sensor, active Canon EF mount, built-in motorized ND at 0/2/4/6 stops. Records to CFast 2.0, SD UHS-II or external USB-C storage. Native camera battery is NP-F570.", battery_type: "NP-F570", card_type: "CFast 2.0 / SD UHS-II / external USB-C storage" },
 { name: "BMPCC 6K Full Frame", model: "Blackmagic Cinema Camera 6K", url: "https://www.blackmagicdesign.com/products/blackmagiccinemacamera/techspecs", description: "Blackmagic Cinema Camera 6K: 6048x4032 full-frame sensor, native L mount, Blackmagic RAW recording to CFexpress Type B or external USB-C storage. Native battery is NP-F570. This is a different body from the Super 35 EF-mount Pocket 6K Pro.", battery_type: "NP-F570", card_type: "CFexpress Type B / external USB-C storage" },
] as const;
